name: staging-on-push

on:
  push:
    branches:
      - master-stage-1

jobs:
  pre-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3.5.2

      - name: Setup Node ENV
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          check-latest: true

      - name: Install Dependencies
        run: yarn

      - name: Run Linter
        run: yarn lint

      - name: Run Test App
        run: yarn test